[package]
name = "ragnarok"
description = "UI Events processor. Originally made for Freya but works for other libraries."
version = "0.5.0-rc.9"
edition = "2024"
license = "MIT"
authors = ["Marc Espín <mespinsanz@gmail.com>"]
readme = "./README.md"
homepage = "https://freyaui.dev/"
repository = "https://github.com/marc2332/freya"
keywords = ["gui", "ui"]
categories = ["gui"]

[lints]
workspace = true

[dependencies]
euclid = { version = "0.22.9", default-features = false }
itertools = { version = "0.14.0", default-features = false, features = [
  "use_alloc",
] }
tracing = { version = "0.1.41", default-features = false }
rustc-hash = { version = "2.1.1", default-features = false }
hashbrown = { version = "0.16.1", default-features = false }

# Performance
hotpath = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
  "euclid/std",
  "itertools/use_std",
  "tracing/std",
  "tracing/attributes",
  "rustc-hash/std",
]
hotpath = ["std", "dep:hotpath", "hotpath/hotpath"]
