name-template: "Release v$RESOLVED_VERSION 🦀"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    label: "feature"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "♻️ Refactor"
    label: "refactor"
  - title: "📝 Documentation"
    label: "documentation"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "dependencies"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: feature
    branch:
      - "/^feat(ure)?[/-].+/"
  - label: bug
    branch:
      - "/^fix[/-].+/"
  - label: refactor
    branch:
      - "/(refactor|refactoring)[/-].+/"
  - label: documentation
    branch:
      - "/doc(s|umentation)[/-].+/"
  - label: chore
    branch:
      - "/^chore[/-].+/"