[package]
name = "freya-router"
authors = ["Jonathan Kelley", "Evan Almloff", "Marc Espín <mespinsanz@gmail.com>"]
version = "0.4.0"
edition = "2021"
description = "Router management for Freya apps"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/marc2332/freya/"
keywords = ["gui", "ui", "desktop", "skia", "dioxus"]

[package.metadata.docs.rs]
features = ["freya-engine/mocked-engine", "docs"]

[dependencies]
dioxus-lib = { workspace = true }

freya-router-macro = { workspace = true }
freya-hooks = { workspace = true }
freya-elements = { workspace = true }

tracing = { workspace = true }
urlencoding = "2.1.3"
url = "2.5.4"
rustversion = "1.0.21"

[dev-dependencies]
freya-testing = { workspace = true }
freya-engine = { workspace = true }
freya = { workspace = true }
tokio = { workspace = true }
freya-router = { workspace = true }

[features]
skia-engine = ["freya-engine/skia-engine"]
