pr_comment = "on_change"

[functions]
min_percent_total = 2

[functions.alloc]
judged = true
min_percent_change = 20
metrics = ["avg", "total"]
min_calls = 10

[functions.timing]
judged = true
min_percent_change = 35
metrics = ["avg", "total"]
min_calls = 15
