name: Deploy book
on:
  push:
    paths:
      - 'book/**/*'
      - '.github/workflows/deploy_book.yml'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@ee69d230fe19748b7abf22df32acaa93833fad08 # v2.0.0
        with:
          mdbook-version: '0.4.32'

      - run: mdbook build
        working-directory: book

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@7bded90d0d09cd99bbfb513966146315db97618b # 1.13.1
        with:
          project: freya-book
          entrypoint: https://deno.land/std/http/file_server.ts
          root: book/book
