name: Deploy docs
on:
  push:
    paths:
      - 'crates/**/*'
      - '.github/workflows/deploy_docs.yml'

env:
  RUSTDOCFLAGS: "-D warnings"

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "docs"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install just
        uses: taiki-e/install-action@cca35edeb1d01366c2843b68fc3ca441446d73d3 # v2.77.1
        with:
          tool: just
      - name: Get nightly toolchain version
        run: echo "NIGHTLY_TOOLCHAIN=$(just rv-nightly)" >> $GITHUB_ENV
      - name: Install nightly Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
        with:
          toolchain: ${{ env.NIGHTLY_TOOLCHAIN }}
          components: rustfmt
      - name: cargo doc
        run: RUSTDOCFLAGS="--cfg docsrs" RUSTUP_TOOLCHAIN=$NIGHTLY_TOOLCHAIN cargo doc --no-deps --workspace --features "all, docs"

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@7bded90d0d09cd99bbfb513966146315db97618b # 1.13.1
        with:
          project: freya-docs
          entrypoint: https://deno.land/std/http/file_server.ts
          root: target/doc
