name: Dioxus Rust
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 */3 * *

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - name: Install latest nextest release
      uses: taiki-e/install-action@nextest
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@v2
      with:
        prefix-key: "8"
    - name: Install linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev
    - name: Use Dioxus main branch
      run: |
        git apply ./patches/dioxus_main_branch.patch
        cargo update
    - name: Check examples
      run: cargo check --examples
    - name: Lint
      run: cargo clippy --workspace -- -D warnings
    - name: Run tests
      run: cargo nextest run --workspace --exclude examples
    - name: Run doctests
      run: cargo test --workspace --doc
