name: Rust Android Build

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  ANDROID_NDK_HOME: /home/runner/android-ndk-r26d
  ANDROID_NDK: /home/runner/android-ndk-r26d

jobs:
  android:
    runs-on: ubuntu-latest
    concurrency:
      group: rust-android-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 2
          submodules: true
      - name: Remove unused programs
        run: |
          sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL
      - name: Install NDK r26d
        run: |
          curl -sSfL -o ndk.zip https://dl.google.com/android/repository/android-ndk-r26d-linux.zip
          unzip -q ndk.zip -d /home/runner
          rm ndk.zip
      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
        with:
          target: aarch64-linux-android, x86_64-linux-android
      - name: Install cargo-ndk
        run: cargo install cargo-ndk
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
      - name: Set up cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        if: github.ref != 'refs/heads/main'
        with:
          shared-key: "rust-android"
          save-if: ${{ github.ref == 'refs/heads/main' }}
      - name: Build Android example
        working-directory: examples/android/AndroidApp
        run: ./gradlew buildRelease