name: Rust Build

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: rust-build-${{ github.ref_name }}
      cancel-in-progress: true

    steps:

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 2
        submodules: true
    - name: Install linux dependencies
      run: sudo apt update && sudo apt install build-essential libssl-dev pkg-config libglib2.0-dev libgtk-3-dev libudev-dev libxdo-dev libwebkit2gtk-4.1-dev
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
    - name: Install just
      uses: taiki-e/install-action@cca35edeb1d01366c2843b68fc3ca441446d73d3 # v2.77.1
      with:
        tool: just
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        shared-key: "rust-ubuntu-latest"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Build all --features
      run: just ba

  build-macos:
    runs-on: macos-latest
    concurrency:
      group: rust-build-macos-${{ github.ref_name }}
      cancel-in-progress: true

    steps:

    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 2
        submodules: true
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1
    - name: Install just
      uses: taiki-e/install-action@cca35edeb1d01366c2843b68fc3ca441446d73d3 # v2.77.1
      with:
        tool: just
    - name: Set up cargo cache
      uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      with:
        shared-key: "rust-macos-latest"
        save-if: ${{ github.ref == 'refs/heads/main' }}

    - name: Build all --features
      run: just ba
