name: Website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "website/**"
      - "crates/**"
      - "examples/web/**"
      - ".github/workflows/website.yml"
  pull_request:
    paths:
      - "website/**"
      - "crates/**"
      - "examples/web/**"
      - ".github/workflows/website.yml"

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: website-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true

      - name: Install stable rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
        with:
          target: wasm32-unknown-emscripten

      - name: Set up cargo cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          shared-key: "web-demo"
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install emsdk
        uses: mymindstorm/setup-emsdk@6ab9eb1bda2574c4ddb79809fc9247783eaf9021 # v14
        with:
          version: 4.0.0
          actions-cache-folder: emsdk-cache

      - name: Install just
        uses: extractions/setup-just@f8a3cce218d9f83db3a2ecd90e41ac3de6cdfd9b # v3

      - name: Build the demo
        run: just web-demo

      - name: Deploy
        uses: amondnet/vercel-action@de09aeac2ace6599ec9b11ef87558759a496bac4 # v42.3.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: website
          vercel-args: ${{ github.ref == 'refs/heads/main' && '--prod' || '' }}
